import type {GithubProvider} from "../../providers/github";

export enum Providers {
  GITHUB = 'github',
  GITLAB = 'gitlab',
  BITBUCKET = 'bitbucket',
}

export type ProviderValues = `${Providers}`;

export type ProviderInstance = GithubProvider;

export enum TypesActions {
  CREATED = 'created',
  EDITED = 'edited',
  DELETED = 'deleted',
  REREQUESTED = 'rerequested',
  COMPLETED = 'completed',
  REQUESTED_ACTION = 'requested_action',
  TRANSFERRED = 'transferred',
  PINNED = 'pinned',
  UNPINNED = 'unpinned',
  LABALED = 'labeled',
  UNLABALED = 'unlabeled',
  LOCKED = 'locked',
  UNLOCKED = 'unlocked',
  CATEGORY_CHANGED = 'category_changed',
  ANSWERED = 'answered',
  UNANSWERED = 'unanswered',
  OPENED = 'opened',
  CLOSED = 'closed',
  REOPENED = 'reopened',
  ASSIGNED = 'assigned',
  UNASSIGNED = 'unassigned',
  MILESTONED = 'milestoned',
  DEMILESTONED = 'demilestoned',
  UPDATED = 'updated',
  MOVED = 'moved',
  SYNCHRONIZE = 'synchronize',
  CONVERTED_TO_DRAFT = 'converted_to_draft',
  ENQUEUED = 'enqueued',
  DEQUEUED = 'dequeued',
  READY_FOR_REVIEW = 'ready_for_review',
  REVIEW_REQUESTED = 'review_requested',
  REVIEW_REQUESTED_REMOVED = 'review_requested_removed',
  AUTO_MERGE_ENABLED = 'auto_merge_enabled',
  AUTO_MERGE_DISABLED = 'auto_merge_disabled',
  SUBMITTED = 'submitted',
  DISMISSED = 'dismissed',
  PUBLISHED = 'published',
  UNPUBLISHED = 'unpublished',
  PRERELEASED = 'prereleased',
  RELEASED = 'released',
  STARTED = 'started',
  REQUESTED = 'requested',
  IN_PROGRESS = 'in_progress',
  CHECKS_REQUESTED = 'checks_requested',
}

export enum ActionsEventTrigger {
  BRANCH_PROTECTION_RULE = 'branch_protection_rule',
  CHECK_RUN = 'check_run',
  CHECK_SUITE = 'check_suite',
  CREATE = 'create',
  DELETE = 'delete',
  DEPLOYMENT = 'deployment',
  DEPLOYMENT_STATUS = 'deployment_status',
  DISCUSSION = 'discussion',
  DISCUSSION_COMMENT = 'discussion_comment',
  FORK = 'fork',
  GOLLUM = 'gollum',
  ISSUE_COMMENT = 'issue_comment',
  ISSUES = 'issues',
  LABEL = 'label',
  MERGE_GROUP = 'merge_group',
  MILESTONE = 'milestone',
  PAGE_BUILD = 'page_build',
  PROJECT = 'project',
  PROJECT_CARD = 'project_card',
  PROJECT_COLUMN = 'project_column',
  PUBLIC = 'public',
  PULL_REQUEST = 'pull_request',
  PULL_REQUEST_REVIEW = 'pull_request_review',
  PULL_REQUEST_REVIEW_COMMENT = 'pull_request_review_comment',
  PULL_REQUEST_TARGET = 'pull_request_target',
  PUSH = 'push',
  REGISTRY_PACKAGE = 'registry_package',
  RELEASE = 'release',
  REPOSITORY_DISPATCH = 'repository_dispatch',
  SCHEDULE = 'schedule',
  STATUS = 'status',
  WATCH = 'watch',
  WORKFLOW_CALL = 'workflow_call',
  WORKFLOW_DISPATCH = 'workflow_dispatch',
  WORKFLOW_RUN = 'workflow_run',
}